
# {{ title }}

```{r}
pdat = remove_group_data(dat[!is.na(dat[["{{ iv }}"]]),], "{{ dv.dif }}", "{{ iv }}")

pdat.long <- rbind(pdat[,c("id","{{ iv }}")], pdat[,c("id","{{ iv }}")])
pdat.long[["{{ pivot.key }}"]] <- c(rep("pre", nrow(pdat)), rep("pos", nrow(pdat)))
pdat.long[["{{ pivot.key }}"]] <- factor(pdat.long[["{{ pivot.key }}"]], c("pre","pos"))
pdat.long[["{{ pivot.value }}"]] <- c(pdat[["{{ dv.pre }}"]], pdat[["{{ dv.pos }}"]])

y.position.min <- abs(
  max(pdat.long[["{{ pivot.value }}"]])
  - min(pdat.long[["{{ pivot.value }}"]]))/15

lvars = as.list(c("{{ dv.dif }}","{{ dv.pos }}","{{ dv.pre }}"))
names(lvars) = unlist(lvars)
```

## Pre-test and Post-test PairWise comparisons for: *{{ pivot.value }} ~ {{ iv }}*

```{r}
pwc.long <- group_by(pdat.long, {{ iv }}) %>%
  pairwise_wilcox_test({{ pivot.value }} ~ {{ pivot.key }}, detailed = T)

df <- pwc.long[,c(".y.","{{ iv }}","group1","group2","n1","n2","estimate",
                  "statistic","p.adj","p.adj.signif")]
```

```{r, echo=FALSE, purl=FALSE}
kable(df)
```

### Plot using p.adj as information

```{r, dpi=300, fig.width={{ pfig.width }}, fig.height={{ pfig.height }}}
stat.test <- pwc.long %>% add_xy_position(x = "{{ pivot.key }}", fun = "mean_ci")
stat.test$y.position <- stat.test$y.position + y.position.min

gg <- ggline(
  pdat.long, x = "{{ pivot.key }}", y = "{{ pivot.value }}", size = 1.5,
  facet.by = "{{ iv }}", add = c("mean_ci"), color = "{{ iv }}",
  position = position_dodge(width = 0.3), palette = color[["{{ iv }}"]])

pdat.long$xj = jitter(as.numeric(pdat.long[["{{ pivot.key }}"]]), amount=.1)
pdat.long$yj = jitter(pdat.long[["{{ pivot.value }}"]], amount = .01)

gg + geom_point(
  data = pdat.long, aes_string(x="xj",y="yj", color = "{{ iv }}"), size=0.5) +
  stat_pvalue_manual(
    stat.test, tip.length = 0, hide.ns = T, label.size = 5,
    position = position_dodge(width = 0.3),
    label = "{ p.adj } ({ p.adj.signif })") + xlab("") +
  coord_cartesian(ylim = c(min(pdat.long$yj), max(pdat.long$yj))) +
  theme(strip.text = element_text(size = 14),
        axis.text = element_text(size = 14))
```

### New Plot using diferences as information


```{r, dpi=300, fig.width={{ pfig.width }}, fig.height={{ pfig.height }}}
stat.test <- pwc.long %>% add_xy_position(x = "{{ pivot.key }}", fun = "mean_ci")

stat.test$r <- sapply(abs(stat.test$estimate)/{{ max.y }}, FUN = function(x) {
   ifelse(x < 0.0001, "<1%", paste0(round(x*100,2), "%"))
})

gg <- ggline(
  pdat.long{{ plot.filter }}, x = "time", y = "score", size = 2,
  facet.by = "{{ iv }}", add = c("mean_ci"), color = "{{ iv }}",
  palette = color[["{{ iv }}"]]) +
  stat_pvalue_manual(
    stat.test, tip.length = 0, hide.ns = T, label.size = 5,
    position = position_dodge(width = 0.3),
    label = "{ r } ({ p.adj.signif })") +
  ggplot2::ylab("")

gg + theme(strip.text = element_text(size = 14),
           axis.text = element_text(size = 14))
```


## Kruskal and Wilcoxon PairWise comparisons for: *{{ pivot.value }} ~ {{ iv }}*


```{r}
kt <- lapply(lvars, FUN = function(x) {
  kruskal_test(pdat, as.formula(paste0(x," ~ {{ iv }}")))  
})

df <- do.call(rbind.fill, lapply(lvars, function(x) {
  add_significance(merge(
    kt[[x]], kruskal_effsize(pdat, as.formula(paste0(x," ~ {{ iv }}"))),
    by = c(".y.","n"), suffixes = c("",".ez")))
}))

df <- df[,c(".y.","n","df","statistic","p","p.signif","effsize","magnitude")]
```

```{r, echo=FALSE, purl=FALSE}
kable(df)
```


```{r}
pwc <- lapply(lvars, FUN = function(x) {
  pairwise_wilcox_test(pdat, as.formula(paste0(x," ~ {{ iv }}")), detailed = T)  
})

df <- do.call(rbind.fill, pwc)
```


```{r, echo=FALSE, purl=FALSE}
kable(df)
```

## Plots to compare pre- and post results

```{r}
plots <- lapply(lvars, FUN = function(y) {
  stat.test <- pwc[[y]] %>% add_xy_position(x = "{{ iv }}")
  stat.test$y.position <- stat.test$y.position + y.position.min
  ggboxplot(pdat, x = "{{ iv }}", y = y, fill = "{{ iv }}",
            palette = color[["{{ iv }}"]]) +
    stat_pvalue_manual(stat.test, tip.length = 0, hide.ns = T, label.size = 5,
                       label="{ p.adj } ({ p.adj.signif })") + xlab("")
})
```


```{r, dpi=300, fig.width={{ fig.width*2 }}, fig.height={{ fig.height }}}
egg::ggarrange(plots[["{{ dv.pre }}"]], plots[["{{ dv.pos }}"]], nrow = 1)
```

## Plot to compare diferences of pre-post

```{r, dpi=300, fig.width={{ fig.width }}, fig.height={{ fig.height }}}
plots[["{{ dv.dif }}"]] +
  labs(subtitle = get_test_label(kt[["{{ dv.dif }}"]], detailed = T),
       caption = get_pwc_label(pwc[["{{ dv.dif }}"]])) +
  ylab("{{ pivot.value }} (dif)")  +
  theme(strip.text = element_text(size = 14),
        axis.text = element_text(size = 14))
```


## Plots for  learning gain with percentages


```{r, dpi=300, fig.width={{ fig.width }}, fig.height={{ fig.height }}}
stat.test <- pwc${{ dv.dif }} %>% add_xy_position(x = "{{ iv }}", fun = "mean_ci")

stat.test$r <- sapply(abs(stat.test$estimate), FUN = function(x) {
   ifelse(x < 0.0001, "<1%", paste0(round(x*100,2), "%"))
})

gg <- ggline(
  pdat, x = "{{ iv }}", y = "{{ dv.dif }}", size = 2, add = c("mean_ci"),
  color = "{{ iv }}", palette = color[["{{ iv }}"]]) +
  stat_pvalue_manual(
    stat.test, tip.length = 0, hide.ns = T, label.size = 5,
    label = "{ r } ({ p.adj.signif })") +
  ggplot2::ylab("")

gg + theme(strip.text = element_text(size = 14),
           axis.text = element_text(size = 14))
```


